import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';
import React from 'react';

const rubik = Rubik({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700', '800', '900'] });

export const metadata: Metadata = {
    title: 'Weather App',
    description: 'Generated by me'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `try{if(new URLSearchParams(location.search).get('mono')==='1'){document.documentElement.classList.add('mono-init');document.documentElement.classList.add('invert');}}catch(e){}`
                    }}
                />
            </head>
            <body className={rubik.className}>{children}</body>
        </html>
    );
}
